# A list of devices you want to take the screenshots from
devices([
  "iPhone SE",
  "iPhone 8",
  "iPhone 8 Plus"
])

# A list of supported languages
languages([
  'en-US',
  'ka-GE'
])

# Where should the resulting screenshots be stored?
output_directory "./fastlane/screenshots"

# Clears previous screenshots
clear_previous_screenshots true

# Latest version of iOS
ios_version '11.3'
